sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n test-env -c qiime2 python=$PYTHON_VERSION qiime nose flake8
  - source activate test-env
  - conda install -c r r
  - conda install -c bioconda bioconductor-dada2
  - pip install .
script:
  - nosetests
  - flake8 q2_dada2 setup.py
